### ISSUE TITLE
Seems didnt work in windbg preview

### ISSUE THREAD

**Issue by bopin2020** [tinysec/jswd#10]
Test it on windbg 10.0.22621.AMD64, it works well, but break windbg enginee in windbg preview.
![image](https://github.com/tinysec/jswd/assets/49940777/04206cf2-b72a-42b3-8fcd-aba969ab3ae9)

![af2e6f7422fb348eb83468cf4b0582d](https://github.com/tinysec/jswd/assets/49940777/0ff03537-99d6-46fc-a559-5645748eef51)

BTW this extension library whether invoke javascript code through windbg enginee inside as well as chakra enginee?  I haven't read this project code.

**Comment by tinysec** [comment]
yes it's use chakra. sorry i am not test with windbg preview , but no plan to support it.
you can use the classic native version.
